### ISSUE TITLE
Swift5.1不是可以利用@PropertyWrapper 这个特性做扩展吗？

### ISSUE THREAD

**Issue by josercc** [bannzai/UserDefaultsGenerator#15]
做这个库意义何在？
比如声明
```swift
@UserDefault("age",0)
var age:Int

//set
self.age = 18
//get
self.age
```

**Comment by bannzai** [comment]
@josercc 

`UserDefualtsGenerator` can be customized for generated swift code with your own stencil template. You can select to use `@PropertyWrapper`, `extension UserDefaults` or more testable code with protocol. For example.


```swift
public protocol BoolLocalStorage {
  func set(_ value: Bool, forKey key: UDGBoolKey) 
  func get(forKey key: UDGBoolKey) -> Bool
}

extension UserDefaultsGenerator: BoolLocalStorage {
  public  func set(_ value: Bool, forKey key: UDGBoolKey)  { ... }
  public func get(forKey key: UDGBoolKey) -> Bool { ... } 
}
```

See more detail to README about`udg generate` option.
https://github.com/bannzai/UserDefaultsGenerator#udg-generate-command-option-description

 And This library user not necessary to write boiler plate swift code. If you want to add or remove `UserDefaults` functions, you only write yml file and exec `udg generate` command. So, it is easy and integrate format of `UserDefaultsGenerate` functions format for your project.

**Comment by bannzai** [comment]
This issue close.
